### ISSUE TITLE
No instrumentation detected

### ISSUE THREAD

**Issue by NikParam42** [jwilk/python-afl#12]
### Hi! 
 
Do I understand correctly that python-afl is instrumenting the code at the time of calling `afl.init()`??

In AFL (for c/c++), I would call the afl-gcc compiler to instrumentalize, but how do I instrumentalize python code?

```
import json
import os
import sys

import afl
afl.init()

stdin_compat = sys.stdin

# data=json.parse(stdin_compat)   //for example

print(stdin_compat)

os._exit(0)
```
and

![cyber_main](https://user-images.githubusercontent.com/57091545/73857743-68b8ad00-4848-11ea-92df-30dc492ea46c.jpg)

how do I fix this error?

**Comment by jwilk** [comment]
This program doesn't do anything, so there's nothing to instrument.
