### ISSUE TITLE
PROGRAM ABORT : No instrumentation detected  

### ISSUE THREAD

**Issue by researcher111** [jwilk/python-afl#17]
I am currently trying to get py-alf-fuzz to run on small program. However, I get the following error: No instrumentation detected. Does anyone know what's wrong? 
![image](https://user-images.githubusercontent.com/3280585/95796911-1c1d4f80-0cbc-11eb-87f5-3addf74dede9.png)

**Comment by Bubble-mt** [comment]
The code you written may have some problems. The parameters you inputed are error.
![image](https://user-images.githubusercontent.com/72586297/95809300-0867fc80-0d41-11eb-86cc-870a697410aa.png)

Change the input paramters,  it can execute successfully.
![image](https://user-images.githubusercontent.com/72586297/95809530-9e9c2280-0d41-11eb-9bfd-a374bdfc3751.png)

 
You could debug the code directly to check problems without executing py-afl-fuzz.

**Comment by researcher111** [comment]
Thanks so much this really helpful. It fixed the problem. I also needed to run program using python3.
